version: '3.8'

services:
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.load_balancer
    ports:
      - "5000:5000"
    container_name: my_load_balancer
    depends_on:
      - server_1
      - server_2
      - server_3

  server_1:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: my_server_1
    environment:
      - SERVER_ID=1

  server_2:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: my_server_2
    environment:
      - SERVER_ID=2

  server_3:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: my_server_3
    environment:
      - SERVER_ID=3
