version: '3.8'

services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile.loadbalancer
    ports:
      - "5000:5000"
    networks:
      - app-network

  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=1
    networks:
      - app-network

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=2
    networks:
      - app-network

  server3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
